### ISSUE TITLE
Namada internal testnet 1 tracking issue

### ISSUE THREAD

**Issue by cwgoes** [anoma/anoma#1005]
Primary testnet purpose: test shielded transactions, specifically:
- Shielding transfer (send from unshielded address to shielded address)
- Shielded transfer (send from shielded address to shielded address)
- Unshielding transfer (send from shielded address to unshielded address)
- Query shielded token balance
- (regular transparent transfers)
- (regular proof-of-stake actions)

Validation may not be complete, but the shielded transfers should be creating & verifying real proofs.

Internal testnet launch blockers:
- [ ] WASM fixes (ref https://github.com/anoma/anoma/pull/1003)
- [ ] List of genesis keys & balances from which to generate a genesis file (https://github.com/anoma/anoma/issues/1004)
- [ ] Docs page on docs.anoma.network with testnet setup & shielded tx instructions (@gnosed @SimSaladin @murisi)

Please join the #namada-internal-testnet-1 channel on Heliax Slack for coordination.

**Comment by tzemanovic** [comment]
done
