### ISSUE TITLE
Juvix Cairo Integration

### ISSUE THREAD

**Issue by mariari** [anoma/anoma#1259]
customer: @mariari
performer: @XuyangSong 
deadline: null
estimated: null
started: null
actual: null
completed: null
confirmed: null
dependencies:
- [x] anoma/green#248 
- [x] anoma/green#249 
- [x] anoma/green#250 
- [x] anoma/green#268 
- [x] anoma/green#488 
- [x] anoma/green#563 
- [x] anoma/green#495 
- [x] anoma/green#390 
- [x] anoma/anoma-archive#1275 
- [x] anoma/green#644 
- [x] anoma/anoma-archive#1271 
- [x] anoma/green#591 
- [x] anoma/green#594 
- [x] anoma/green#495 
- [x] anoma/green#715 
- [x] anoma/green#705 
- [x] anoma/green#706 
- [x] anoma/anoma-archive#1278 
- [x] anoma/green#709 

---

We should have the RM in Juvix working in Cairo and hooked up in our system:

anoma/green#488 tracks that our worker has the right interface and anoma/green#268 tracks that the compliance circuit is done. Thus this tracks that Juvix contracts can go through the system end to end properly 

Note that anoma/green#248 is an alternative to anoma/green#249 and anoma/green#250, and is something that is mostly done but we should upgrade it to anoma/green#249 and anoma/green#250.

The image in this post is a snapshot from when we first mapped the issue, see replies for more up to date maps:

![無標題-2023-06-20-1630(2)](https://github.com/anoma/anoma-archive/assets/32526923/6c0b4d3c-84c6-4c31-a136-450d89fe9a18)

Excalidraw Link

https://excalidraw.com/#json=1t5CMF365cupPM71a9Z7y,6o4ik6qox21E2YoonuDDgw

**Comment by XuyangSong** [comment]
all done and merged
