### ISSUE TITLE
advance base ledger prototype version 2

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#143]
This is tracking issue for tasks for the next phase as described in https://github.com/heliaxdev/anoma-prototype/tree/master/tech-specs/src/explore/prototypes#advancing-a-successful-prototype

Some sub-tasks:
- [x] review file by file and add issues for necessary updates #267
- [ ] add unit tests (and/or property-based, depending on the use-case) and integration tests with main focus on well-specified behavior
- [ ] if the prototype has diverged from the original design or something is missing, update these pages
- [x] review tx/VP execution #169 
- [x] make it possible to use storage without RocksDB connection for unit tests (maybe add a trait for Storage to be used in the protocol, which can be mocked for unit tests)
- [x] consider adding validation layer for protobuf types with nicer types (protobuf 3 default fields are `Option`al, validation layer could provide nicer types to work with)
- [x] remove fixed-length read functions #170
- [x] Tx storage writes - check account exists #152 
- [x] refactor wasm code - Define types/const for wasm return codes, better reuse in env functions
- [x] add `make doc` to the CI, update docstrings and fix warnings
- [x] reserved storage key prefixes #148 
- [x] VP validation on init account and on VP update #156
- [x] update transparent addresses #164 
- [x] wasm procedural macros #166 
- [x] wasm deterministic builds #154 and #239
- [x] choose different names for the extern host functions wasm #187 
- [x] refactor Value in storage/types.rs #190 
- [x] tx - add timestamp #195 
- [x] Graceful shutdown #28
- [x] Wasm memory limits #84
- [x] refactor wasm runners #245 
- [ ] add missing rust docstring #258
- [x] VP gas meter bug #259
- [x] add timestamp to SignedTxData #266
- [x] chain ID in storage #268
- [x] fix storage keys for verifiers VPs added by a tx #292
- [x] #318

**Comment by tzemanovic** [comment]
I'm closing this and moving the open issue #258 into #125
