### ISSUE TITLE
Playnet prep

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#168]
For the internal “playnet”, we will allow anyone who’s like to participate to run anoma node and/or intent broadcaster with matchmaker. 

We’ll create genesis accounts with some XANs and ed25519 keys. We don’t yet have wallet (#167), so we can pre-generate them for now and in-line them in code and ask participants to only use their own keys.

We should write a small tutorial on how to write transactions/VPs/intents and how to inject them on chain. This can be a page added to the tech-spec.

We could also build the rust doc for the host env functions that are available in wasm and host it somewhere.

We should also check and ensure that node and intent broadcaster can discover peers or configure these beforehand.

It would be nice to close these issues from anoma/anoma#143 first for a decent UX:
- [x] anoma/anoma#169 
- [x] anoma/anoma#170
- [x] anoma/anoma#148
- [x] anoma/anoma#156 
- [x] anoma/anoma#164 
- [x] anoma/anoma#152 
- [ ] anoma/anoma#166 (this can be postponed, the work-around is to write wasm implementation outside of the entrypoint macro)
- [x] anoma/anoma#171
- [ ] anoma/anoma#176 (this can be postponed)
- [x] anoma/anoma#179 
- [ ] anoma/anoma#177 (this can be postponed)

Then we can tag the "playnet" branch.
