### ISSUE TITLE
code reviews

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#267]
This is a tracking issue for reviewing code base following the completion of prototype v2.

- [x] shared
  - [x] ledger - done in the team call on 3/6/2021
  - [x] gossip - done in the team call on 15/7/2021
  - [x] types - done in the team call on 10/6/2021
  - [x] vm
    - [x] mod - done in the team call on 24/6/2021
    - [x] host_env - done in the team call on 24/6/2021
    - [x] memory, types, prefix_iter - done in the team call on 1/7/2021
    - [x] wasm - done in the team call on 1/7/2021
- [x] vm_env - done in the team call on 8/7/2021
- [x] vm_macro - done in the team call on 8/7/2021
- [x] apps lib
  - [x] node/gossip - done in the team call on 22/7/2021
  - [x] gossiper - done in the team call on 22/7/2021
  - [x] node/ledger/{mod,shell,tendermint_node} - done in the team call on 29/7/2021
  - [x] node/ledger/storage - done in the team call on 5/8/2021
  - [x] other - done in the team call on 5/8/2021
