### ISSUE TITLE
Release engineering

### ISSUE THREAD

**Issue by juped** [anoma/anoma#375]
Tasks necessary to get release engineering in order for testnet deployment:

* [ ] Finalize Anoma crate organization at the Rust build system level
* [x] Select a pre-1.x version numbering scheme
* [ ] Internally set up release signing keys
* [x] Internally decide on a release cadence
* [x] Internally decide what binaries to provide with a release (and automate these builds)
* [x] Write a release procedure (look at cargo-release?)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763024116906) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
done
