### ISSUE TITLE
base ledger prototype version 2

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma#62]
This is tracking issue for the base ledger prototype version 2 (a follow-up to base ledger prototype version 1 https://github.com/heliaxdev/rd-pm/issues/5).

I think if we're happy with prototype version 2, we could start the next phase described in https://github.com/heliaxdev/anoma-prototype/tree/master/tech-specs/src/explore/prototypes#advancing-a-successful-prototype

Let's agree on prototype plan anoma/anoma#63 first.

Steps:
- storage
  - [x] anoma/anoma#6 
  - [ ] anoma/anoma#4 - non-blocking for now
  - [x] anoma/anoma#5
  - [x] anoma/anoma#64
- wasm
  - [x] anoma/anoma#16
  - [ ] anoma/anoma#21 (tracking issue with sub-steps)
  - [x] anoma/anoma#14 (gas)
  - [x] anoma/anoma#18 (gas)
  - [x] anoma/anoma#136 (gas)
  - [x] anoma/anoma#15 
  - [x] anoma/anoma#17 
  - [x] anoma/anoma#22 - we have basic wasm validation sufficient for now, but the issue is left open for improvements
  - validity predicates 
    - [x] anoma/namada#3 - we can skip for now as without PoS the validators VPs cannot do much
    - [x] anoma/anoma#67
    - [x] anoma/anoma#68
  - [x] potentially anoma/anoma#24 
- For the orderbook
  - [x] anoma/anoma#73
  - [x] anoma/anoma#35 
- [x] anoma/anoma#10
- [x] gas counter anoma/anoma#65
- [x] anoma/anoma#111 VP gas
- [x] anoma/anoma#23
- [x] anoma/anoma#66
- [x] anoma/anoma#69
- [x] anoma/anoma#71 
- [x] anoma/anoma#75 
- [x] anoma/anoma#101 
- [x] anoma/anoma#104
- [ ] potentially anoma/anoma#72
