### ISSUE TITLE
Tracking: IBC integration

### ISSUE THREAD

**Issue by yito88** [anoma/anoma#898]
Related to #866 

### IBC native VP
- [x] Validate IBC-related data [#327]
- [ ] Set and validate "clients/{identifier}/connections" [#696]
- [ ] Misbehavior
- [x] Add a native VP to check escrow/unescrow/burn/mint token in a token transfer [#823]

### Proof
- [x] Modify MerkleTree for ICS23 proof verification [#671]
- [x] Query data with the proof [#498]

### IBC-related transaction
- [x] [IBC transaction](https://github.com/anoma/anoma/blob/f6e78278608aaef253617885bb7ef95a50057268/wasm/wasm_source/src/lib.rs#L219-L233) calls just `dispatch` function with data which is an encoded IBC message
- [ ] Handling functions for a transaction [#411](https://github.com/anoma/anoma/issues/411)
  - [x] IBC-related operations are implemented in `IbcActions`[#720]
  - [x] Implement `IbcActions` for `vm_env` (which calls just `vm_env::imports::read_bytes`, `write_bytes` etc.) [#823]
  - [x] IBC message as a transaction data [#719]
  - [ ] [BLOCKED] Building IBC transaction with WASM
      - Need the next release version v0.12.0 of `ibc-rs`
        - Tried with ibc-rs master -> IBC transaction could be built (some fixes are needed to update for v0.12.0)

### ICS20 FungibleTokenTransfer
- [x] sending/receiving tokens [#823]
  - [Design](https://hackmd.io/@heliax/ByH8Fp73t)

### Others
- [x] Emit an IBC event [#480]
- [ ] Update `ibc-rs` to v0.11.0 to call the latest proof verification functions [#863]

### Relayer (in [heliaxdev/ibc-rs](https://github.com/heliaxdev/ibc-rs))
- [NEED TEST] Add ChainEndpoint of Anoma
  - [Rebased and fixed the prototype relayer with the latest ibc-rs](https://github.com/heliaxdev/ibc-rs/tree/yuji/rebase_v0.23.5_anoma)

## Integration test
- [x] [Tests with vm_host_env](https://github.com/anoma/anoma/blob/master/tests/src/vm_host_env/mod.rs)

## E2E test
- [ ] Add e2e tests for IBC between two Anoma chains without a relayer
- [ ] Add e2e tests for between Anoma and other chains (in `heliaxdev/ibc-rs`?)

### Test targets
- Client
  - Create, update, upgrade
  - Invalid client states are rejected
    - Invalid ClientState
    - Invalid ConsensusState
    - Invalid proof
- Connection
  - Handshake to open a connection
  - Invalid requests are rejected
    - Invalid connection state change
    - Invalid proof
- Channel
  - Handshake to open a channel
  - Close a channel
  - Close a channel due to timeout
  - Invalid requests are rejected
    - Invalid channel state change
    - Invalid proof
- ICS20 Token transfer
  - Token transfer (escrow/unescrow/mint/burn)
  - Refund due to timeout or ack failure
  - Invalid requests are rejected
    - Unrelated token transfer in the transaction
    - Invalid packet(invalid transfer data)

### Target chains
- Anoma <-> Anoma
- Anoma <-> Cosmos
- ...
